import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
    ],

    theme: {
        extend: {
            colors: {
                fc: {
                    navy: 'var(--fc-navy)',
                    blue: 'var(--fc-blue)',
                    'blue-soft': 'var(--fc-blue-soft)',
                    bg: 'var(--fc-bg)',
                    red: 'var(--fc-red)',
                    'red-dark': 'var(--fc-red-dark)',
                    text: 'var(--fc-text)',
                    muted: 'var(--fc-muted)',
                    border: 'var(--fc-border)',
                    white: 'var(--fc-white)',
                },
                background: 'var(--color-background)',
                surface: 'var(--color-surface)',
                text: 'var(--color-text)',
                muted: 'var(--color-muted)',
                border: 'var(--color-border)',
                primary: 'var(--color-primary)',
                link: 'var(--color-link)',
                focus: 'var(--color-focus)',
                danger: 'var(--color-danger)',
                'danger-accent': 'var(--color-danger-accent)',
                gray: {
                    50: 'var(--fc-blue-soft)',
                    100: 'var(--fc-bg)',
                    200: 'var(--fc-border)',
                    300: 'var(--fc-border)',
                    400: 'var(--fc-muted)',
                    500: 'var(--fc-muted)',
                    600: 'var(--fc-muted)',
                    700: 'var(--fc-text)',
                    800: 'var(--fc-text)',
                    900: 'var(--fc-text)',
                    950: 'var(--fc-navy)',
                },
                indigo: {
                    50: 'var(--fc-blue-soft)',
                    100: 'var(--fc-blue-soft)',
                    200: 'var(--fc-border)',
                    300: 'var(--fc-border)',
                    400: 'var(--fc-blue)',
                    500: 'var(--fc-blue)',
                    600: 'var(--fc-blue)',
                    700: 'var(--fc-navy)',
                    800: 'var(--fc-navy)',
                    900: 'var(--fc-navy)',
                    950: 'var(--fc-navy)',
                },
                blue: {
                    50: 'var(--fc-blue-soft)',
                    100: 'var(--fc-blue-soft)',
                    200: 'var(--fc-border)',
                    300: 'var(--fc-border)',
                    400: 'var(--fc-blue)',
                    500: 'var(--fc-blue)',
                    600: 'var(--fc-blue)',
                    700: 'var(--fc-blue)',
                    800: 'var(--fc-navy)',
                    900: 'var(--fc-navy)',
                    950: 'var(--fc-navy)',
                },
                sky: {
                    50: 'var(--fc-blue-soft)',
                    100: 'var(--fc-blue-soft)',
                    200: 'var(--fc-border)',
                    300: 'var(--fc-border)',
                    400: 'var(--fc-blue)',
                    500: 'var(--fc-blue)',
                    600: 'var(--fc-blue)',
                    700: 'var(--fc-blue)',
                    800: 'var(--fc-navy)',
                    900: 'var(--fc-navy)',
                    950: 'var(--fc-navy)',
                },
                red: {
                    50: 'var(--fc-blue-soft)',
                    100: 'var(--fc-blue-soft)',
                    200: 'var(--fc-border)',
                    300: 'var(--fc-border)',
                    400: 'var(--fc-red)',
                    500: 'var(--fc-red)',
                    600: 'var(--fc-red)',
                    700: 'var(--fc-red-dark)',
                    800: 'var(--fc-red-dark)',
                    900: 'var(--fc-red-dark)',
                    950: 'var(--fc-red-dark)',
                },
                green: {
                    50: 'var(--fc-blue-soft)',
                    100: 'var(--fc-blue-soft)',
                    200: 'var(--fc-border)',
                    300: 'var(--fc-border)',
                    400: 'var(--fc-blue)',
                    500: 'var(--fc-blue)',
                    600: 'var(--fc-blue)',
                    700: 'var(--fc-navy)',
                    800: 'var(--fc-navy)',
                    900: 'var(--fc-navy)',
                    950: 'var(--fc-navy)',
                },
            },
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
